
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(712, 764)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 411, 751))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(-30, 0, 391, 721))
        self.label.setTabletTracking(False)
        self.label.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.label.setAcceptDrops(False)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("png.png"))
        self.label.setObjectName("label")
        self.line_3 = QtWidgets.QFrame(self.tab)
        self.line_3.setGeometry(QtCore.QRect(130, 180, 111, 21))
        self.line_3.setMidLineWidth(1)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(130, 40, 111, 21))
        self.line.setMidLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_5 = QtWidgets.QFrame(self.tab)
        self.line_5.setGeometry(QtCore.QRect(90, 740, 151, 21))
        self.line_5.setMidLineWidth(1)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.LEGe = QtWidgets.QComboBox(self.tab)
        self.LEGe.setGeometry(QtCore.QRect(40, 470, 74, 20))
        self.LEGe.setMouseTracking(True)
        self.LEGe.setAcceptDrops(True)
        self.LEGe.setAutoFillBackground(False)
        self.LEGe.setEditable(True)
        self.LEGe.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.LEGe.setMinimumContentsLength(0)
        self.LEGe.setDuplicatesEnabled(False)
        self.LEGe.setFrame(True)
        self.LEGe.setObjectName("LEGe")
        self.LEGe.addItem("")
        self.LEGe.addItem("")
        self.LEGe.addItem("")
        self.LEGe.addItem("")
        self.LEGe.activated.connect(self.LEGGe)
        self.line_4 = QtWidgets.QFrame(self.tab)
        self.line_4.setGeometry(QtCore.QRect(110, 470, 101, 21))
        self.line_4.setMidLineWidth(1)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.BodyE = QtWidgets.QComboBox(self.tab)
        self.BodyE.setGeometry(QtCore.QRect(10, 180, 122, 20))
        self.BodyE.setMouseTracking(True)
        self.BodyE.setAcceptDrops(True)
        self.BodyE.setAutoFillBackground(False)
        self.BodyE.setEditable(True)
        self.BodyE.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.BodyE.setMinimumContentsLength(0)
        self.BodyE.setDuplicatesEnabled(False)
        self.BodyE.setFrame(True)
        self.BodyE.setObjectName("BodyE")
        self.BodyE.addItem("")
        self.BodyE.addItem("")
        self.BodyE.addItem("")
        self.BodyE.addItem("")
        self.BodyE.addItem("")
        self.BodyE.addItem("")
        self.BodyE.activated.connect(self.Bodyye)
        self.ArmE = QtWidgets.QComboBox(self.tab)
        self.ArmE.setGeometry(QtCore.QRect(30, 230, 81, 20))
        self.ArmE.setMouseTracking(True)
        self.ArmE.setAcceptDrops(True)
        self.ArmE.setAutoFillBackground(False)
        self.ArmE.setEditable(True)
        self.ArmE.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.ArmE.setMinimumContentsLength(0)
        self.ArmE.setDuplicatesEnabled(False)
        self.ArmE.setFrame(True)
        self.ArmE.setObjectName("ArmE")
        self.ArmE.addItem("")
        self.ArmE.addItem("")
        self.ArmE.addItem("")
        self.ArmE.addItem("")
        self.ArmE.activated.connect(self.Armme)
        self.line_2 = QtWidgets.QFrame(self.tab)
        self.line_2.setGeometry(QtCore.QRect(90, 230, 71, 21))
        self.line_2.setMidLineWidth(1)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.FOe = QtWidgets.QComboBox(self.tab)
        self.FOe.setGeometry(QtCore.QRect(50, 690, 104, 20))
        self.FOe.setMouseTracking(True)
        self.FOe.setAcceptDrops(True)
        self.FOe.setAutoFillBackground(False)
        self.FOe.setEditable(True)
        self.FOe.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.FOe.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.FOe.setMinimumContentsLength(0)
        self.FOe.setDuplicatesEnabled(False)
        self.FOe.setFrame(True)
        self.FOe.setObjectName("FOe")
        self.FOe.addItem("")
        self.FOe.addItem("")
        self.FOe.addItem("")
        self.FOe.addItem("")
        self.FOe.addItem("")
        self.FOe.activated.connect(self.FOOe)
        self.line_11 = QtWidgets.QFrame(self.tab)
        self.line_11.setGeometry(QtCore.QRect(110, 690, 101, 21))
        self.line_11.setMidLineWidth(1)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.HandE = QtWidgets.QComboBox(self.tab)
        self.HandE.setGeometry(QtCore.QRect(30, 350, 100, 20))
        self.HandE.setMouseTracking(True)
        self.HandE.setAcceptDrops(True)
        self.HandE.setAutoFillBackground(False)
        self.HandE.setEditable(True)
        self.HandE.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.HandE.setMinimumContentsLength(0)
        self.HandE.setDuplicatesEnabled(False)
        self.HandE.setFrame(True)
        self.HandE.setObjectName("HandE")
        self.HandE.addItem("")
        self.HandE.addItem("")
        self.HandE.addItem("")
        self.HandE.addItem("")
        self.HandE.activated.connect(self.Handde)
        self.line_12 = QtWidgets.QFrame(self.tab)
        self.line_12.setGeometry(QtCore.QRect(90, 360, 31, 21))
        self.line_12.setMidLineWidth(1)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.line_14 = QtWidgets.QFrame(self.tab)
        self.line_14.setGeometry(QtCore.QRect(100, 400, 141, 21))
        self.line_14.setMidLineWidth(1)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.GAE = QtWidgets.QComboBox(self.tab)
        self.GAE.setGeometry(QtCore.QRect(0, 400, 133, 20))
        self.GAE.setMouseTracking(True)
        self.GAE.setAcceptDrops(True)
        self.GAE.setAutoFillBackground(False)
        self.GAE.setEditable(True)
        self.GAE.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.GAE.setMinimumContentsLength(0)
        self.GAE.setDuplicatesEnabled(False)
        self.GAE.setFrame(True)
        self.GAE.setObjectName("GAE")
        self.GAE.addItem("")
        self.GAE.addItem("")
        self.GAE.addItem("")
        self.GAE.addItem("")
        self.GAE.addItem("")
        self.GAE.activated.connect(self.GAAe)
        self.HeadE = QtWidgets.QComboBox(self.tab)
        self.HeadE.setEnabled(True)
        self.HeadE.setGeometry(QtCore.QRect(76, 40, 101, 20))
        self.HeadE.setMouseTracking(True)
        self.HeadE.setAcceptDrops(True)
        self.HeadE.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.HeadE.setAutoFillBackground(False)
        self.HeadE.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStatesMinorOutlyingIslands))
        self.HeadE.setInputMethodHints(QtCore.Qt.ImhNone)
        self.HeadE.setEditable(True)
        self.HeadE.setInsertPolicy(QtWidgets.QComboBox.InsertBeforeCurrent)
        self.HeadE.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.HeadE.setMinimumContentsLength(0)
        self.HeadE.setDuplicatesEnabled(False)
        self.HeadE.setFrame(True)
        self.HeadE.setObjectName("HeadE")
        self.HeadE.addItem("")
        self.HeadE.addItem("")
        self.HeadE.addItem("")
        self.HeadE.addItem("")
        self.HeadE.addItem("")
        self.HeadE.addItem("")
        self.HeadE.activated.connect(self.Headde)
        self.label.raise_()
        self.line_3.raise_()
        self.line.raise_()
        self.line_5.raise_()
        self.line_4.raise_()
        self.line_2.raise_()
        self.line_11.raise_()
        self.line_12.raise_()
        self.line_14.raise_()
        self.BodyE.raise_()
        self.ArmE.raise_()
        self.HandE.raise_()
        self.GAE.raise_()
        self.LEGe.raise_()
        self.FOe.raise_()
        self.HeadE.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 361, 721))
        self.label_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("png.png"))
        self.label_2.setObjectName("label_2")
        self.line_6 = QtWidgets.QFrame(self.tab_2)
        self.line_6.setGeometry(QtCore.QRect(230, 410, 31, 21))
        self.line_6.setMidLineWidth(1)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.tab_2)
        self.line_7.setGeometry(QtCore.QRect(140, 60, 111, 21))
        self.line_7.setMidLineWidth(1)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.tab_2)
        self.line_8.setGeometry(QtCore.QRect(150, 690, 91, 21))
        self.line_8.setMidLineWidth(1)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.tab_2)
        self.line_9.setGeometry(QtCore.QRect(160, 510, 91, 21))
        self.line_9.setMidLineWidth(1)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(self.tab_2)
        self.line_10.setGeometry(QtCore.QRect(150, 230, 91, 21))
        self.line_10.setMidLineWidth(1)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_13 = QtWidgets.QFrame(self.tab_2)
        self.line_13.setGeometry(QtCore.QRect(220, 270, 51, 21))
        self.line_13.setMidLineWidth(1)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.GAk = QtWidgets.QComboBox(self.tab_2)
        self.GAk.setGeometry(QtCore.QRect(220, 370, 134, 20))
        self.GAk.setMouseTracking(True)
        self.GAk.setAcceptDrops(True)
        self.GAk.setAutoFillBackground(False)
        self.GAk.setEditable(True)
        self.GAk.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.GAk.setMinimumContentsLength(0)
        self.GAk.setDuplicatesEnabled(False)
        self.GAk.setFrame(True)
        self.GAk.setObjectName("GAk")
        self.GAk.addItem("")
        self.GAk.addItem("")
        self.GAk.addItem("")
        self.GAk.addItem("")
        self.GAk.addItem("")
        self.GAk.activated.connect(self.GAAk)
        self.line_15 = QtWidgets.QFrame(self.tab_2)
        self.line_15.setGeometry(QtCore.QRect(140, 370, 91, 21))
        self.line_15.setMidLineWidth(1)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.HeadE_2 = QtWidgets.QComboBox(self.tab_2)
        self.HeadE_2.setEnabled(True)
        self.HeadE_2.setGeometry(QtCore.QRect(250, 60, 101, 20))
        self.HeadE_2.setMouseTracking(True)
        self.HeadE_2.setAcceptDrops(True)
        self.HeadE_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.HeadE_2.setAutoFillBackground(False)
        self.HeadE_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStatesMinorOutlyingIslands))
        self.HeadE_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.HeadE_2.setEditable(True)
        self.HeadE_2.setInsertPolicy(QtWidgets.QComboBox.InsertBeforeCurrent)
        self.HeadE_2.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.HeadE_2.setMinimumContentsLength(0)
        self.HeadE_2.setDuplicatesEnabled(False)
        self.HeadE_2.setFrame(True)
        self.HeadE_2.setObjectName("HeadE_2")
        self.HeadE_2.addItem("")
        self.HeadE_2.addItem("")
        self.HeadE_2.addItem("")
        self.HeadE_2.addItem("")
        self.HeadE_2.addItem("")
        self.HeadE_2.addItem("")
        self.HeadE_2.activated.connect(self.HeadE_22)
        self.BodyE_2 = QtWidgets.QComboBox(self.tab_2)
        self.BodyE_2.setGeometry(QtCore.QRect(240, 230, 122, 20))
        self.BodyE_2.setMouseTracking(True)
        self.BodyE_2.setAcceptDrops(True)
        self.BodyE_2.setAutoFillBackground(False)
        self.BodyE_2.setEditable(True)
        self.BodyE_2.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.BodyE_2.setMinimumContentsLength(0)
        self.BodyE_2.setDuplicatesEnabled(False)
        self.BodyE_2.setFrame(True)
        self.BodyE_2.setObjectName("BodyE_2")
        self.BodyE_2.addItem("")
        self.BodyE_2.addItem("")
        self.BodyE_2.addItem("")
        self.BodyE_2.addItem("")
        self.BodyE_2.addItem("")
        self.BodyE_2.addItem("")
        self.BodyE_2.activated.connect(self.BodyE_22)
        self.ArmE_2 = QtWidgets.QComboBox(self.tab_2)
        self.ArmE_2.setGeometry(QtCore.QRect(270, 270, 81, 20))
        self.ArmE_2.setMouseTracking(True)
        self.ArmE_2.setAcceptDrops(True)
        self.ArmE_2.setAutoFillBackground(False)
        self.ArmE_2.setEditable(True)
        self.ArmE_2.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.ArmE_2.setMinimumContentsLength(0)
        self.ArmE_2.setDuplicatesEnabled(False)
        self.ArmE_2.setFrame(True)
        self.ArmE_2.setObjectName("ArmE_2")
        self.ArmE_2.addItem("")
        self.ArmE_2.addItem("")
        self.ArmE_2.addItem("")
        self.ArmE_2.addItem("")
        self.ArmE_2.activated.connect(self.ArmE_22)
        self.HandE_2 = QtWidgets.QComboBox(self.tab_2)
        self.HandE_2.setGeometry(QtCore.QRect(260, 410, 100, 20))
        self.HandE_2.setMouseTracking(True)
        self.HandE_2.setAcceptDrops(True)
        self.HandE_2.setAutoFillBackground(False)
        self.HandE_2.setEditable(True)
        self.HandE_2.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.HandE_2.setMinimumContentsLength(0)
        self.HandE_2.setDuplicatesEnabled(False)
        self.HandE_2.setFrame(True)
        self.HandE_2.setObjectName("HandE_2")
        self.HandE_2.addItem("")
        self.HandE_2.addItem("")
        self.HandE_2.addItem("")
        self.HandE_2.addItem("")
        self.HandE_2.addItem("")
        self.HandE_2.activated.connect(self.HandE_22)
        self.LEGe_2 = QtWidgets.QComboBox(self.tab_2)
        self.LEGe_2.setGeometry(QtCore.QRect(250, 510, 74, 20))
        self.LEGe_2.setMouseTracking(True)
        self.LEGe_2.setAcceptDrops(True)
        self.LEGe_2.setAutoFillBackground(False)
        self.LEGe_2.setEditable(True)
        self.LEGe_2.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.LEGe_2.setMinimumContentsLength(0)
        self.LEGe_2.setDuplicatesEnabled(False)
        self.LEGe_2.setFrame(True)
        self.LEGe_2.setObjectName("LEGe_2")
        self.LEGe_2.addItem("")
        self.LEGe_2.addItem("")
        self.LEGe_2.addItem("")
        self.LEGe_2.addItem("")
        self.LEGe_2.addItem("")
        self.LEGe_2.activated.connect(self.LEGe_22)
        self.FOe_2 = QtWidgets.QComboBox(self.tab_2)
        self.FOe_2.setGeometry(QtCore.QRect(240, 690, 104, 20))
        self.FOe_2.setMouseTracking(True)
        self.FOe_2.setAcceptDrops(True)
        self.FOe_2.setAutoFillBackground(False)
        self.FOe_2.setEditable(True)
        self.FOe_2.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.FOe_2.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.FOe_2.setMinimumContentsLength(0)
        self.FOe_2.setDuplicatesEnabled(False)
        self.FOe_2.setFrame(True)
        self.FOe_2.setObjectName("FOe_2")
        self.FOe_2.addItem("")
        self.FOe_2.addItem("")
        self.FOe_2.addItem("")
        self.FOe_2.addItem("")
        self.FOe_2.addItem("")
        self.FOe_2.activated.connect(self.FOe_22)
        self.label_2.raise_()
        self.line_6.raise_()
        self.line_7.raise_()
        self.line_8.raise_()
        self.line_9.raise_()
        self.line_10.raise_()
        self.line_13.raise_()
        self.line_15.raise_()
        self.HeadE_2.raise_()
        self.BodyE_2.raise_()
        self.ArmE_2.raise_()
        self.GAk.raise_()
        self.HandE_2.raise_()
        self.LEGe_2.raise_()
        self.FOe_2.raise_()
        self.tabWidget.addTab(self.tab_2, "")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(360, 10, 321, 721))
        self.textEdit.setObjectName("textEdit")
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textEdit.setFont(font)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def LEGGe(self):
        self.textEdit.clear()
        index = self.LEGe.currentIndex()
        if index==1:
            self.textEdit.setPlainText("What is Leg Numbness?\nLeg numbness is an uncomfortable complaint that usually occurs after prolonged sitting or crossing legs, resulting from pressure on the nerves or interruption of blood flow.\n\n\nHow Is Leg Numbness Treated?\nThe treatment for leg numbness varies according to the underlying condition of this condition. Antidepressant derivative drugs may be effective in cases of psychological leg numbness or fibromyalgia-induced leg numbness. While corticosteroid-derived drugs are used in inflammatory conditions, drugs containing gabapentin and pregabalin can be prescribed for the treatment of numbness caused by nerve damage such as MS or diabetic neuropathy.")
        elif index==2:
            self.textEdit.setPlainText("Why Do Legs Cramp?\nCramps can occur normally or as a result of a disease. Cramps are seen in the legs without any reason. The important thing here is that if the event in your tight, painful, cramped leg usually lasts more than 10 minutes, there is a problem that needs to be investigated.\nDehydration of the body is an event that triggers muscle cramps. Abnormal nerve activity is blamed for leg cramps of unknown cause.\n\n\nWhat Should We Do When Cramp Occurs?\nMost leg cramps can be relieved by working the affected muscles. Moving your legs as if you were exercising throughout the day often helps reduce the frequency of cramping attacks.\nAs soon as the legs cramp, it is necessary to stretch and massage the affected muscle. Stretching the leg by keeping it straight, lifting the feet back from the ankle, pulling the toes towards you, or getting out of bed and walking on the heels for a few minutes can cause a cramping fit.")
        elif index==3:
            self.textEdit.setPlainText("What Is Tingling In The Legs?\nIf there are complaints such as unbearable pain descending from your waist to your knee, tingling in the legs, difficulty in moving, the cause may be 'sciatica'. Sciatic pain, also called nerve rheumatism among the people, occurs in the sciatic nerve, which is the largest nerve in the body, and causes severe pain if it is compressed.\n\n\nHow Is Leg Numbness Treated?\nThe treatment for leg numbness varies according to the underlying condition of this condition. Antidepressant derivative drugs may be effective in cases of psychological leg numbness or fibromyalgia-induced leg numbness. While corticosteroid-derived drugs are used in inflammatory conditions, drugs containing gabapentin and pregabalin can be prescribed for the treatment of numbness caused by nerve damage such as MS or diabetic neuropathy.\nIn addition to medical treatment, there are various applications that can be done at home that answer the question of 'what is good for leg numbness'. Practices such as resting, massaging the relevant area, maintaining a sleep pattern, following a balanced and healthy diet, and limiting or ending alcohol consumption are among the methods that can be effective in controlling the complaint of numbness in the legs.\nYou should be aware of the need for urgent medical attention in case of a blunt pain sensation in the numb area, spreading from the leg to the groin, accompanied by severe complaints such as difficulty in walking and speaking.")
    def Bodyye(self):
        self.textEdit.clear()
        index = self.BodyE.currentIndex()
        if index==1:
            self.textEdit.setPlainText("What causes itching and redness in the body?\nBody redness and itching are most commonly caused by dry skin. The redness on the body and the accompanying flaking and cracking appearance indicate that the skin is dehydrated. Redness on the skin may occur due to bathing in extremely hot water, staying in the sun for a long time, insufficient fluid consumption, medications used and environmental conditions.\n\n\nHow does itching and redness in the body go?\nTo treat redness and itching in the body, you should balance the moisture content of your skin. Start by drinking water to hydrate your skin.\nBy protecting your skin from the cold in winter, you can prevent dryness and cracking of the skin. You can solve the problems such as redness on the hand, redness and dryness on the arm, which we also suffer from, especially in the winter season, with a moisturizer. In addition to consuming plenty of fluids, moisturize your entire body at least once a day with an intensely moisturizing body cream.")
        elif index==2:
            self.textEdit.setPlainText("What is itching on the body?\nItching, which can be felt in all or part of the body, is a feeling that can be seen in everyone. In some cases, itching, which can reach as irritating as pain, can be caused by many health problems. Failure to control itching can lead to progression of the underlying disease, skin problems, insomnia, and even depression. It can cause a person's quality of life to decrease and in some cases to isolate himself from social life. This condition, which can also be seen in the form of itching and swelling in the body, can occur almost anywhere on the body. Itching and blisters in the body can be caused by a wide range of diseases such as insect bites, stress, allergies, parasites, fungi, anemia, diabetes, cancer, blood diseases and drug side effects, as well as skin diseases.\n\n\nHow to treat itching in the body?\nItching in the body, which is one of the disorders that causes the person's quality of life to decrease, disappears with the treatment of the underlying disease that causes itching. Therefore, it is extremely important for people with complaints of itching to consult a specialist physician. The physician performs a physical examination after taking the patient's anamnesis. When it deems necessary, it diagnoses the disease causing itching with additional tests and arranges treatment. Frequently asked 'How does itching in the body go?' The answer to the question can be given in this way. Just like in the treatment of itching, physical examination plays an important role in the treatment of bariatric surgery and may be due to chronic causes.")
        elif index==3:
            self.textEdit.setPlainText("What causes edema?\nEdema occurs because the tiny blood vessels (capillaries) in your body leak fluid. The leaking fluid is around the vein. accumulates in the tissues and causes swelling. Edema, which occurs in heart, liver and kidney diseases, is caused by the inability to remove salt, which holds the excess fluid in the body.\n\n\nHow is edema treated?\nMild edema usually goes away on its own. It is possible to accelerate the process by keeping the affected limb above the level of the heart. In the presence of more severe edema, it can be treated with drugs called diuretics, which help the body to remove excess fluid accumulated in the body through urine. However, since these drugs can cause side effects, they are used considering the general health status of the patient. These drugs offer a short-term solution. For permanent treatment, the factor causing edema should be determined and eliminated. For example, if edema has developed due to drug use, it may be necessary to discontinue them and start other drugs.")
        elif index==4:
            self.textEdit.setPlainText("What causes chest pain?\nWhen there is chest pain, the person's first thought is often that they are having a heart attack. While chest pain is an important symptom of a heart attack, it can also be caused by relatively less serious conditions. About 13% of visits to the emergency room for chest pain are due to a serious heart-related problem.\n\n\nHow are causes of chest pain diagnosed?\nThe key to diagnosis is the patient's medical history. Knowledge of the nature of the pain gives the doctor an idea of ​​what should be excluded and what is more likely. Understanding the nature of the pain, its severity, associated symptoms, and the risk factors present in the patient provides guidance in evaluating the likelihood of a potential cause and which diagnoses should be considered. To make a diagnosis, the doctor must know the type of pain and how much pain the person is experiencing. For this purpose, questions that can be asked to patients include:")
        elif index==5:
            self.textEdit.setPlainText("What is shortness of breath?\nShortness of breath, along with fatigue, is one of the most common complaints of patients. Shortness of breath means that the person is unable to breathe or has difficulty breathing. In other words, people think that their oxygen needs are not enough or that they are blocked while breathing. Other than that, some people may describe it as a heaviness and pressure in the chest. Shortness of breath can be divided into subjective and objective. Objective dyspnea is based on objective parameters. Oxygen level in the blood, blood gas or breathing rate during physical examination are the main criteria.\n\n\nHow is the treatment of shortness of breath planned?\nThere are widely used treatment methods for shortness of breath. However, it is of great importance to find the underlying disease and to plan the treatment for this picture under expert control. In the treatment of shortness of breath, first of all, if the person has gained weight, he/she should lose weight, if he/she smokes, quit smoking, and if his/her condition is low, he/she should be directed to exercises to increase the condition or to physical therapy.")
    def Armme(self):
        self.textEdit.clear()
        index = self.ArmE.currentIndex()
        if index==1:     
            self.textEdit.setPlainText("What is cramp?\nCramping, also known as muscle spasm, is involuntary pain or contractions in the muscles. Muscles contract and relax to provide movement. Cramping occurs when a muscle contracting for movement contracts again without relaxing, or when the brain has problems transmitting the relaxation signal to the muscles. Unwanted and sudden muscle contractions can be observed in many muscle groups at the same time. Although cramps are more common in the front leg, hind leg and lower leg, they can also occur in the stomach, arms and hands. Everyone encounters cramping problem at least once in their life. It is more common in people who are involved in a particular sport, especially cyclists, marathon runners, and athletes.\n\n\nHow does the cramp go?\nCramping usually goes away with stretching movements applied to the muscles in the area where the cramp is experienced. In calf cramps, pushing the wall with both hands by pressing the heels on the ground and taking the cramped leg back half a step or pulling the foot from the ankle to the body in the lying position also help the cramp to pass. Gentle massage and hot compresses applied to the muscles help relax the muscles. If the cause of the muscle spasm is fluid and electrolyte loss, this loss must be replaced.")    
        elif index==2:
            self.textEdit.setPlainText("What is joint pain?\nAlthough joint pain is more common in older people, it is a health problem that can be encountered in younger individuals as well. Joint pain, which begins to appear with advancing age, is usually due to the decrease in joint fluid or the loss of strength of the cartilage tissue. Obesity, injuries and some diseases, intense sports activities can lead to joint damage and pain. Rarely, pain caused by psychological problems may also occur.\n\n\nWhat are the treatment methods for joint pain?\nHow to treat joint pain depends on the type of disease causing the pain. In addition to the symptomatic treatment applied to alleviate the pain and the accompanying negativities in the treatment, additional treatment should be applied for the disease causing the pain. Joint pain caused by rheumatic diseases can be treated with various drugs and physical therapy applications. Even spas are recommended for the treatment of some rheumatic diseases. It is very important to maintain weight control by eating regularly, as excess weight will cause more fatigue on the joints. Therefore, prevention of excessive weight gain is an important treatment method.")
        elif index==3:
            self.textEdit.setPlainText("What Are the Causes of Muscle Pain?\nMuscle pain, or in other words, soft tissue rheumatism, can occur either with strain on the muscles or with a disorder in the body's pain interpretation mechanisms such as fibromyalgia.\nOther diseases in which muscle pain is a prominent finding are myofascial pain syndrome polymyalgiaaromatica, myopathies and deficiencies of some vitamins such as vitamin D and some minerals such as magnesium. Iron deficiency anemia and thyroid disorders can also cause muscle pain complaints.\n\n\nWhat Should a Person Who Feels Muscle Pain Do?\nIn a person who feels muscle pain, first of all, it should be determined whether the pain is a local pain or a widespread pain.\nSince the cause of widespread pain may be rheumatic diseases such as fibromyalgia and myofascial pain syndrome, polymyalgiaaromatica or vitamin deficiencies, necessary tests should be performed after a good examination in such pains.\nIn regional muscle pain, the onset time of the pain and whether it is associated with any trauma should be determined. Traumas can be a major trauma such as a blow to the muscle or a fall, as well as unit traumas caused by the accumulation of repetitive small movements, which we call micro trauma. When a relationship is established with such a trauma, the patient can be followed up with muscle rest and cold application first.")
    def FOOe(self):
        self.textEdit.clear()
        index = self.FOe.currentIndex()
        if index==1:   
            self.textEdit.setPlainText("What is Foot Fungus?\nFoot fungus, which can be defined as a fungal infection that occurs in the foot area of ​​the body, mostly develops between the toes. However, athlete's foot can also occur on the upper surface, side or back of the foot. This disorder, which is extremely common in society, is one of the health problems experienced by almost every individual once in a lifetime.\nFoot fungus initially causes red dots and scaly appearance on the skin surface. Following this situation, water-filled sacs occur on the feet. Extremely itchy bumps can take on an inflamed appearance. There may be rash and redness in the form of dandruff on the soles of the feet.\n\n\nHow to Treat Foot Fungus?\nThe priority in the treatment of athlete's foot is to protect foot health. In other words, the foot should be kept away from the environment where fungus can be transmitted. Feet should be washed regularly on a daily basis and thoroughly dried with a clean towel each time. Wearing shoes suitable for the season and changing socks when necessary are extremely effective in the treatment of athlete's foot.")
        elif index==2:
            self.textEdit.setPlainText("What Causes Foot Odor?\nNot the sweat itself, but the bacteria that comes with it, which is the main cause of bad foot odour. In addition to bacteria, fungal infection also causes the formation of a strong odor on the feet. Some medications used, hormonal changes during puberty or pregnancy; Metabolic diseases such as obesity, stress and hyperthyroidism also cause the body to produce more sweat, triggering foot odor. At the same time, genetic factors are also effective in foot odor.\n\n\nHow to Treat Foot Odor: With Sage!\nSage leaves have the feature of preventing foot odor. For this, you can put sage leaves in your shoes that you will use the night before.")
        elif index==3:
            self.textEdit.setPlainText("What Causes Ingrown Nails?\nAlthough ingrown nails are seen at the same rate in both men and women, it has been observed that it is more common in individuals with sweaty feet as a result of researches. In addition, elderly individuals are at higher risk, especially as toenails thicken with age.\n\n\nWhat is the treatment of ingrown nail?\nUninfected cases of ingrown toenails can be treated at home under normal circumstances. However, in cases where the toenail pierces the skin or shows any signs of infection, it is recommended to seek medical attention. Signs of infection include redness, swelling, warmth and pus.\nTo treat an ingrown nail, an individual can try soaking their feet in warm soapy water for about 15 to 20 minutes three to four times a day. But at other times the fingers should be kept dry. Placing a cotton ball dipped in olive oil into the space between the nail and the skin can help open up.")
        elif index==4:
            self.textEdit.setPlainText("What causes callus?\nCallus (callus and clavus) is the hardening and thickening of the skin that occurs as a result of the skin being under pressure and compression. Calluses can occur either due to the pressure of the bone protrusion under it or due to the pressure and compression applied to the same point constantly. Especially in cases such as the use of wrong shoes on the soles of the feet, the selection of inappropriate insoles, calluses may occur at the points where the body weight is most concentrated. If there is an anatomical deterioration in the bone structure, then calluses can also be observed.\n\n\nCallus Treatment\nCalluses can be treated using salicylic acid-containing mixtures, solutions, pomades and ready-made callus bands, which have the ability to dissolve the keratin layer of the skin. In cases where these applications are not sufficient, surgical removal of calluses, electrocautery or cryotherapy can be used to destroy them. Calluses can grow if left untreated. As a result of the addition of pain and infection, treatment can be difficult. Especially for patients with peripheral vascular disease, circulatory disorder and diabetes, calluses should be treated by specialist physicians. It should be kept in mind that wounds starting under the calluses in these patients may cause serious complications such as loss of limb.")
    def Handde(self):
        self.textEdit.clear()
        index = self.HandE.currentIndex()
        if index==1:  
            self.textEdit.setPlainText("What Causes Hand Cracking?\nHand care is a very important issue. Our hands can be damaged for many reasons, just like our face. Hands that are extremely open to external influences; It dries up in winter due to cold and harsh weather and can also be affected by extremely hot weather in summer. The main reason for hand cracking and drying is the loss of moisture due to external factors. Hands affected by summer and winter weather changes are left without moisture. Hands that are sensitive to cold and hot water can be extremely worn out, except for the seasonal factor. Cracks and wrinkles occur on the skin.\n\n\nWhat's Good for Cracked Hands?\nThe main cause of hand cracking is the lack of moisture in the skin. The first way to moisturize our skin is to consume plenty of water. If you do not meet your daily water needs, you may see dryness and cracking in certain parts of your body. Hand cracking is an example of this.\nAnother method that can be good for cracked hands is to use moisturizing creams and lotions. With OSL Hydrosoft Lotion, developed for both face and body, you can provide the moisture your hands need.")
        elif index==2:
            self.textEdit.setPlainText("How to understand a finger fracture?\nFingers, which are used for activities such as holding and grasping in the bone system, are one of the most sensitive points of the body. Finger fracture due to osteoporosis disease or environmental reasons goes unnoticed for a long time. Trauma, sports, workplace injury, falls or other accidents are the main causes of finger fractures.\n\n\nHOW IS FINGER FRACTURE TREATMENT DONE?\nFinger fractures require serious treatment. Even with a small breakage, it should be intervened immediately as it affects finger movements. Intervention varies with hands and feet. An x-ray is taken to determine the point where the fracture is. Then, an appropriate method is selected for the deformity caused by the fracture. Since the fracture experienced in finger fracture also affects other finger crowns, stabilizer treatment is applied to prevent the foot or hand from moving. Sensitive fingers are a little more difficult to re-weld than other bones. The scratch is fixed to the area where the broken bone is with screws, single and plate. It takes 4 or 6 weeks on average. In this process, not only drugs, but also the person should consume milk, greens and plenty of fruit.")
        elif index==3:
            self.textEdit.setPlainText("What Causes Nail Breakage?\nNails are like biomarkers of the body. The cause of nail breakage may be environmental factors to which the nails are exposed. However, some medical conditions detected in the body as a result of examinations and tests by the doctor may also be among the causes of nail breakage.\n\n\nWhat Is Good For Nail Breakage?\n'What's good for nail breakage?' In order to give a clear answer to the question 'Why does nail breakage happen?' The answer to the question should be sought. For this, you must go to the doctor's examination. Your doctor can apply the necessary treatment after performing the appropriate scans. If you observe that your nails are unhealthy, you can help prevent it with some home care strategies.")
    def GAAe(self):
        self.textEdit.clear()
        index = self.GAE.currentIndex()
        if index==1:     
            self.textEdit.setPlainText("What is Urinary Tract Infection?\nIn urinary tract infection, symptoms such as pain or burning sensation when urinating, the need to urinate frequently, an urgent or sudden need to urinate, or blood in the urine may be seen. In kidney infection, symptoms such as fever, back pain, nausea or vomiting may occur. Most urinary tract infections can be treated with antibiotic pills. Antibiotics work by killing the bacteria that cause the infection. In bladder infections, antibiotics usually need to be used for 3 to 7 days, while in kidney infections, antibiotics may need to be used for a longer time (up to 2 weeks). While simple infections are treated as outpatients, hospitalization may be necessary in kidney infections, so it is absolutely necessary to apply to health institutions after the appearance of symptoms.\n\n\nWhat are Urinary Tract Infection Treatment Methods?\nThe antibiotic treatment to be chosen in urinary tract infections varies depending on whether the disease is complicated or simple. In addition, the antibiotic treatment to be used at the beginning can be selected according to the conditions such as allergy or side effect profile of the patients. Antibiotics such as nitrofurantoin, trimethoprim-sulfamethoxazole and fosfomycin can be used as the first treatment in the treatment of acute simple cystitis. Alternatively, beta-lactam group antibiotics or fluoroquinolones can be preferred. According to the results of the test, the type of antibiotic given can be changed in people who have had urine culture and sensitivity test, and antibiotics that act directly on the bacteria can be started. In complicated urinary tract infections, urine culture and antibiotic resistance test are performed in all patients. Depending on the severity of the disease and other risk factors, antibiotic treatment is started without waiting for the culture result, but the treatment is shaped according to the culture and antibiotic resistance. Hospitalization can be made for the treatment and follow-up of patients with severe conditions.")
        elif index==2:
            self.textEdit.setPlainText("What is an inguinal hernia?\nHernia is a disease that can be seen in all ages and genders, from newborn babies to older people. The areas where the hernia is seen are mostly the places where the abdominal wall is weak. In inguinal hernia, it is the protrusion of one of the abdominal organs, mostly a part of the intestine, from a weak point of the peritoneum wall in the inguinal part, under the skin. The hernia, which is visible in the groin area initially due to increased intra-abdominal pressure when standing, sneezing, coughing, straining and straining, becomes invisible when the person lies down. However, if it is not treated, the hernia expands and swelling increases. It does not heal on its own over time with the help of nutrition and diet, exercise or medication.\n\n\nInguinal hernia treatment\nThere is no drug treatment for inguinal hernia and the only treatment method is surgery. However, people with inoperable physiology and elderly patients may rarely use inguinal ligaments in line with the physician's recommendation. The inguinal ligament restricts the movements of the legs and prevents the hernia from coming out by creating a buffer on the hernia. However, if it comes out from the edge of the inguinal ligament, it can get stuck and cause the hernia to suffocate. Therefore, surgery should be preferred if possible. The aim of hernia surgery is to place the hernia in the abdomen, to eliminate the formation of a pouch, to close the cavity that causes the exit, and to repair the defect in the abdominal wall in order to prevent its recurrence.")
        elif index==3:
            self.textEdit.setPlainText("What is Frequent Urination?\nFrequent urination means that an individual needs to urinate or need to urinate more often than usual during the day. However, the order expressed by the concept of 'frequent' varies from person to person. In this direction, in order for frequent urination to be accepted as a clinical disorder, it is examined whether this complaint negatively affects the quality of daily life of the person. Situations such as the sudden need to go to the toilet or the anxiety due to the lack of a toilet nearby may also accompany the complaint of frequent urination.\nThe complaint of frequent urination may develop due to certain physiological or psychological conditions in individuals, as well as among important clinical symptoms that are warning signs for some important health problems. In this regard, people with severely frequent urination complaints should be evaluated by a specialist physician.\n\n\nWhat can be done in the treatment of frequent urination?\nSince an increase in the frequency of urination can be caused by various reasons, it is necessary to evaluate the presence of any health problem by a specialist physician and to clarify the need for treatment. Since bacterial factors are at the forefront in urinary tract infections, antibiotics are used in the treatment. Topical-based antibiotics and antifungal drugs may be considered in vaginal and vulva infections. In people with suspected diabetes, blood glucose measurements should be made and appropriate treatment should be started to ensure glucose control in case the diagnosis is finalized. In conditions that require surgical intervention, such as enlargement of the prostate gland, urogynecological problems or tumors, the treatment should be planned by the physicians of the relevant departments.")
        elif index==4:
            self.textEdit.setPlainText("Wound on the genitals\nIn today's conditions, there has been a much greater increase in wounds on the genitals lately. The causes of these wounds are generally among the sexually transmitted diseases. In some cases, injuries resulting from inflammation are also observed. Itching, pain, burning and stinging in the genital area are among the symptoms that women describe as injuries in the vaginal area. Wounds are frequently encountered in these areas. These injuries make people extremely restless and uncomfortable. Some wounds are mild and some are extremely severe.\n\n\nWhat should I do to protect from wounds in the genitals?\nAlthough people generally think of refusing treatment, you should immediately consult a doctor for wounds on the genitals. Early diagnosis and treatment with the tests to be done after the doctor you will visit without neglect will be beneficial in preventing permanent damage. Wounds on the genitals are generally treated with medication. Being under constant control during this treatment process prevents permanent damage to a large extent.")
    def Headde(self):
        self.textEdit.clear()
        index = self.HeadE.currentIndex()
        if index==1: 
            self.textEdit.setPlainText("What is a headache?\nHeadache occurring in any part of the head is a complaint that all humanity has experienced in some part of their life. Among the reasons for applying to emergency services, it covers 3%. 96% of headaches are benign, but the remaining cases of severe ligament pain are among the emergencies where early intervention is life-saving. Emergency physicians carefully analyze the cases that tend to have this type of course, take the patient's medical history and perform a physical examination. Various laboratory techniques and radiological imaging methods are then used to gain an idea of ​​the underlying condition.\n\n\nHow does the headache go?\nIn case of headache, if there is an underlying health problem (such as sinus infection, etc.), the relevant treatment is taken from the specialist physician. Apart from this, in primary headaches, especially migraine, the neurologist starts the relevant treatment by taking your medical history and examining it.\nThere are many medications to try in the treatment of headaches. The goal in the treatment of migraine is to reduce the triggering factors, to suppress the sensitivity in the nervous system and the events in and around the veins that occur during pain. Basic treatment is divided into two as preventive and attack treatment. Here, the frequency of the patient's pain is effective in the treatment decision. For example, if the patient's pain is seen only once or twice a month, attack treatment is planned for this patient.")
        elif index==2:
            self.textEdit.setPlainText("Causes of vision loss and sudden vision loss\nMajor diseases that cause temporary vision loss include cerebral vascular occlusion and migraine. Permanent vision loss can develop either suddenly or gradually. Sudden vision loss most commonly develops due to occlusion of the eye vessels, intraocular hemorrhages and optic nerve disorders. Gradually developing vision loss is mostly due to conditions such as cataracts, eye defects, diabetes, age-related macular degeneration. Situations such as sudden increase in eye pressure and infection of the eye can also cause permanent vision loss along with pain.\n\n\nWhat are the treatment methods for eye diseases?\nSince eye diseases that cause narrowing of the visual field negatively affect the quality of daily life, it is very important to choose the right treatment methods. Different treatment methods have been developed for congenital eye disorders and vision problems due to environmental factors. For the treatment of the eye problem, which is correctly diagnosed with a detailed eye examination, treatment methods such as the use of glasses, drug therapy, or surgical intervention may be preferred by your doctor.")
        elif index==3:
            self.textEdit.setPlainText("What are the causes of tinnitus?\nNormal tinnitus lasts less than a week and less than five minutes. This is quite common and is something that everyone experiences from time to time. But pathological tinnitus lasts longer than the specified time. Conditions such as constant tinnitus are often accompanied by hearing loss. Subjective tinnitus heard only by the patient can have many causes. As an earwax can cause tinnitus, long-term exposure to loud noise, foreign body, perforation of the eardrum, otitis media, fluid accumulation in the middle ear, damage to the inner ear cells, and hardening of the bones and joints in the middle ear can also cause tinnitus. In addition, hearing loss, allergies, blood pressure changes, a disorder called meniere, diabetes, anemia, menopause, hormonal changes, traumas in the head and neck region, thyroid diseases, vascular enlargement called aneurysm, lesions affecting the nerves that provide hearing, wrong medication use. , neurological, metabolic or psychiatric diseases are also among the answers to the question 'What causes tinnitus'.\n\n\nWhat are the tinnitus treatments?\nAs a result of examinations and tests, the cause of the tinnitus is revealed, and then a personalized treatment plan is made. Advice to reduce tinnitus such as avoiding exposure to loud music, controlling blood pressure, avoiding salty foods, avoiding coffee, cola and cigarette consumption, and exercising are among the best answers to the question of what is good for tinnitus. Since the treatment methods of tinnitus will be shaped depending on the cause of the tinnitus, treatment options are evaluated in a wide range. For example, removing the earwax or foreign body called a plug in the ear canal is therapeutic when this is the cause of tinnitus.")
        elif index==4:
            self.textEdit.setPlainText("What causes a runny nose?\nA runny nose can be caused by anything that irritates the nasal tissues or stimulates the inflammatory process there. Colds, flu, allergies, and various irritants can cause a runny nose. Less common causes of a runny nose may include polyps, foreign body, tumors, or migraine-like headaches.\n\n\nHow does a runny nose go?\nAcupressure. Sinus pain, congestion and associated runny nose can be treated with mild acupressure. Using acupressure on the area around your nose can relieve a runny nose, congestion, and headache. For this purpose, pressure is applied 10 times on each corner of the nose using a light pressure. The same is done in the area just above the eyes. This application is repeated 2-3 times a day to relax the sinuses.")
        elif index==5:
            self.textEdit.setPlainText("What is Sore Throat?\nSore throat describes a feeling of pain, itching, burning sensation and irritation in the throat that gets worse when swallowing. Sore throat is one of the most common symptoms in outpatient clinic admissions. Most sore throats are caused by infection and environmental factors. Although the dry throat feeling can be uncomfortable, the sore throat usually goes away on its own. Sometimes, a sore throat may require treatment depending on the cause and type. Experiencing regular sore throat problems may be a harbinger of diseases, so annual check-up screening will be an effective method. Both patients who wonder how check-up is done and patients who want to learn about the chronic reasons for sore throat can apply to hospitals.\n\n\nHow Does a Sore Throat Pass?\nRest has an important place in the healing of sore throat caused by different diseases. It is also important to rest the vocal cords in sore throat. It is necessary not to speak loudly and not to irritate the throat by not speaking too much unless necessary. In addition, the throat can be moistened by consuming fluids frequently so that the throat does not dry out. Since sore throat can be caused by breathing polluted air, being in a smoking environment or smoking causes sore throat. Various foods can be used to heal a sore throat as soon as possible.")
    def GAAk(self):
        self.textEdit.clear()
        index = self.GAk.currentIndex()
        if index==1: 
            self.textEdit.setPlainText("What is Frequent Urination?\nFrequent urination means that an individual needs to urinate or need to urinate more often than usual during the day. However, the order expressed by the concept of 'frequent' varies from person to person. In this direction, in order for frequent urination to be accepted as a clinical disorder, it is examined whether this complaint negatively affects the quality of daily life of the person. Situations such as the sudden need to go to the toilet or the anxiety due to the lack of a toilet nearby may also accompany the complaint of frequent urination.\nThe complaint of frequent urination may develop due to certain physiological or psychological conditions in individuals, as well as among important clinical symptoms that are warning signs for some important health problems. In this regard, people with severely frequent urination complaints should be evaluated by a specialist physician.\n\n\nWhat can be done in the treatment of frequent urination?\nSince an increase in the frequency of urination can be caused by various reasons, it is necessary to evaluate the presence of any health problem by a specialist physician and to clarify the need for treatment. Since bacterial factors are at the forefront in urinary tract infections, antibiotics are used in the treatment. Topical-based antibiotics and antifungal drugs may be considered in vaginal and vulva infections. In people with suspected diabetes, blood glucose measurements should be made and appropriate treatment should be started to ensure glucose control in case the diagnosis is finalized. In conditions that require surgical intervention, such as enlargement of the prostate gland, urogynecological problems or tumors, the treatment should be planned by the physicians of the relevant departments.")
        elif index==2:
            self.textEdit.setPlainText("What is an inguinal hernia?\nHernia is a disease that can be seen in all ages and genders, from newborn babies to older people. The areas where the hernia is seen are mostly the places where the abdominal wall is weak. In inguinal hernia, it is the protrusion of one of the abdominal organs, mostly a part of the intestine, from a weak point of the peritoneum wall in the inguinal part, under the skin. The hernia, which is visible in the groin area initially due to increased intra-abdominal pressure when standing, sneezing, coughing, straining and straining, becomes invisible when the person lies down. However, if it is not treated, the hernia expands and swelling increases. It does not heal on its own over time with the help of nutrition and diet, exercise or medication.\n\n\nInguinal hernia treatment\nThere is no drug treatment for inguinal hernia and the only treatment method is surgery. However, people with inoperable physiology and elderly patients may rarely use inguinal ligaments in line with the physician's recommendation. The inguinal ligament restricts the movements of the legs and prevents the hernia from coming out by creating a buffer on the hernia. However, if it comes out from the edge of the inguinal ligament, it can get stuck and cause the hernia to suffocate. Therefore, surgery should be preferred if possible. The aim of hernia surgery is to place the hernia in the abdomen, to eliminate the formation of a pouch, to close the cavity that causes the exit, and to repair the defect in the abdominal wall in order to prevent its recurrence.")
        elif index==3:
            self.textEdit.setPlainText("Vaginal Bleeding\nRegular menstrual bleeding in women is a sign of good health. However, when these bleedings go out of normal, that is, bleeding in unexpected moments is called abnormal bleeding. It is impossible to talk about definitive data on who has more frequent abnormal bleeding. This problem can be encountered at almost any age. However, this situation may be more common in young girls who have just started to menstruate.\n\n\nWhat to Do in Case of Irregular Vaginal Bleeding\nFirst of all, know that there is no need to panic. Because most of the bleeding happens for simple reasons. Make sure your bleeding is coming from the vagina or the anus. Then make an appointment with your doctor and notify your doctor by noting the days of bleeding. If you are taking birth control pills or hormone therapy, talk to your doctor and do what he or she says. Another drug may be added or your treatment may change completely. If you are pregnant, inform your doctor immediately.")
        elif index==4:
            self.textEdit.setPlainText("What is vaginal fungus?\nVaginal yeast is a common infection that causes irritation, discharge and extreme itching in the vagina and surrounding tissues called the vulva. This condition, also called vaginal candidiasis, affects 75% of women in the community at least once. Vaginal yeast infections are not considered a sexually transmitted infection because although it can spread sexually, it is more common in sexually inactive women. However, regular sexual activity increases the risk of vaginal yeast infections.\n\n\nHow to treat vaginal fungus?\nEvery fungal infection is different. Therefore, the doctor recommends the most appropriate treatment option for the patient according to the severity of the symptoms. He usually prescribes antifungal creams, ointments, tablets or suppositories for simple fungal infections. In women with a simple yeast infection, symptoms may return within two months of treatment. In this case, it is useful to consult a doctor again.")
    def HeadE_22(self):
        self.textEdit.clear()
        index = self.HeadE_2.currentIndex()
        if index==1: 
            self.textEdit.setPlainText("What is a headache?\nHeadache occurring in any part of the head is a complaint that all humanity has experienced in some part of their life. Among the reasons for applying to emergency services, it covers 3%. 96% of headaches are benign, but the remaining cases of severe ligament pain are among the emergencies where early intervention is life-saving. Emergency physicians carefully analyze the cases that tend to have this type of course, take the patient's medical history and perform a physical examination. Various laboratory techniques and radiological imaging methods are then used to gain an idea of ​​the underlying condition.\n\n\nHow does the headache go?\nIn case of headache, if there is an underlying health problem (such as sinus infection, etc.), the relevant treatment is taken from the specialist physician. Apart from this, in primary headaches, especially migraine, the neurologist starts the relevant treatment by taking your medical history and examining it.\nThere are many medications to try in the treatment of headaches. The goal in the treatment of migraine is to reduce the triggering factors, to suppress the sensitivity in the nervous system and the events in and around the veins that occur during pain. Basic treatment is divided into two as preventive and attack treatment. Here, the frequency of the patient's pain is effective in the treatment decision. For example, if the patient's pain is seen only once or twice a month, attack treatment is planned for this patient.")
        elif index==2:
            self.textEdit.setPlainText("Causes of vision loss and sudden vision loss\nMajor diseases that cause temporary vision loss include cerebral vascular occlusion and migraine. Permanent vision loss can develop either suddenly or gradually. Sudden vision loss most commonly develops due to occlusion of the eye vessels, intraocular hemorrhages and optic nerve disorders. Gradually developing vision loss is mostly due to conditions such as cataracts, eye defects, diabetes, age-related macular degeneration. Situations such as sudden increase in eye pressure and infection of the eye can also cause permanent vision loss along with pain.\n\n\nWhat are the treatment methods for eye diseases?\nSince eye diseases that cause narrowing of the visual field negatively affect the quality of daily life, it is very important to choose the right treatment methods. Different treatment methods have been developed for congenital eye disorders and vision problems due to environmental factors. For the treatment of the eye problem, which is correctly diagnosed with a detailed eye examination, treatment methods such as the use of glasses, drug therapy, or surgical intervention may be preferred by your doctor.")
        elif index==3:
            self.textEdit.setPlainText("What are the causes of tinnitus?\nNormal tinnitus lasts less than a week and less than five minutes. This is quite common and is something that everyone experiences from time to time. But pathological tinnitus lasts longer than the specified time. Conditions such as constant tinnitus are often accompanied by hearing loss. Subjective tinnitus heard only by the patient can have many causes. As an earwax can cause tinnitus, long-term exposure to loud noise, foreign body, perforation of the eardrum, otitis media, fluid accumulation in the middle ear, damage to the inner ear cells, and hardening of the bones and joints in the middle ear can also cause tinnitus. In addition, hearing loss, allergies, blood pressure changes, a disorder called meniere, diabetes, anemia, menopause, hormonal changes, traumas in the head and neck region, thyroid diseases, vascular enlargement called aneurysm, lesions affecting the nerves that provide hearing, wrong medication use. , neurological, metabolic or psychiatric diseases are also among the answers to the question 'What causes tinnitus'.\n\n\nWhat are the tinnitus treatments?\nAs a result of examinations and tests, the cause of the tinnitus is revealed, and then a personalized treatment plan is made. Advice to reduce tinnitus such as avoiding exposure to loud music, controlling blood pressure, avoiding salty foods, avoiding coffee, cola and cigarette consumption, and exercising are among the best answers to the question of what is good for tinnitus. Since the treatment methods of tinnitus will be shaped depending on the cause of the tinnitus, treatment options are evaluated in a wide range. For example, removing the earwax or foreign body called a plug in the ear canal is therapeutic when this is the cause of tinnitus.")
        elif index==4:
            self.textEdit.setPlainText("What causes a runny nose?\nA runny nose can be caused by anything that irritates the nasal tissues or stimulates the inflammatory process there. Colds, flu, allergies, and various irritants can cause a runny nose. Less common causes of a runny nose may include polyps, foreign body, tumors, or migraine-like headaches.\n\n\nHow does a runny nose go?\nAcupressure. Sinus pain, congestion and associated runny nose can be treated with mild acupressure. Using acupressure on the area around your nose can relieve a runny nose, congestion, and headache. For this purpose, pressure is applied 10 times on each corner of the nose using a light pressure. The same is done in the area just above the eyes. This application is repeated 2-3 times a day to relax the sinuses.")
        elif index==5:
            self.textEdit.setPlainText("What is Sore Throat?\nSore throat describes a feeling of pain, itching, burning sensation and irritation in the throat that gets worse when swallowing. Sore throat is one of the most common symptoms in outpatient clinic admissions. Most sore throats are caused by infection and environmental factors. Although the dry throat feeling can be uncomfortable, the sore throat usually goes away on its own. Sometimes, a sore throat may require treatment depending on the cause and type. Experiencing regular sore throat problems may be a harbinger of diseases, so annual check-up screening will be an effective method. Both patients who wonder how check-up is done and patients who want to learn about the chronic reasons for sore throat can apply to hospitals.\n\n\nHow Does a Sore Throat Pass?\nRest has an important place in the healing of sore throat caused by different diseases. It is also important to rest the vocal cords in sore throat. It is necessary not to speak loudly and not to irritate the throat by not speaking too much unless necessary. In addition, the throat can be moistened by consuming fluids frequently so that the throat does not dry out. Since sore throat can be caused by breathing polluted air, being in a smoking environment or smoking causes sore throat. Various foods can be used to heal a sore throat as soon as possible.")
     
    def BodyE_22(self):
        self.textEdit.clear()
        index = self.BodyE_2.currentIndex()
        if index==1:
            self.textEdit.setPlainText("What causes itching and redness in the body?\nBody redness and itching are most commonly caused by dry skin. The redness on the body and the accompanying flaking and cracking appearance indicate that the skin is dehydrated. Redness on the skin may occur due to bathing in extremely hot water, staying in the sun for a long time, insufficient fluid consumption, medications used and environmental conditions.\n\n\nHow does itching and redness in the body go?\nTo treat redness and itching in the body, you should balance the moisture content of your skin. Start by drinking water to hydrate your skin.\nBy protecting your skin from the cold in winter, you can prevent dryness and cracking of the skin. You can solve the problems such as redness on the hand, redness and dryness on the arm, which we also suffer from, especially in the winter season, with a moisturizer. In addition to consuming plenty of fluids, moisturize your entire body at least once a day with an intensely moisturizing body cream.")
        elif index==2:
            self.textEdit.setPlainText("What is itching on the body?\nItching, which can be felt in all or part of the body, is a feeling that can be seen in everyone. In some cases, itching, which can reach as irritating as pain, can be caused by many health problems. Failure to control itching can lead to progression of the underlying disease, skin problems, insomnia, and even depression. It can cause a person's quality of life to decrease and in some cases to isolate himself from social life. This condition, which can also be seen in the form of itching and swelling in the body, can occur almost anywhere on the body. Itching and blisters in the body can be caused by a wide range of diseases such as insect bites, stress, allergies, parasites, fungi, anemia, diabetes, cancer, blood diseases and drug side effects, as well as skin diseases.\n\n\nHow to treat itching in the body?\nItching in the body, which is one of the disorders that causes the person's quality of life to decrease, disappears with the treatment of the underlying disease that causes itching. Therefore, it is extremely important for people with complaints of itching to consult a specialist physician. The physician performs a physical examination after taking the patient's anamnesis. When it deems necessary, it diagnoses the disease causing itching with additional tests and arranges treatment. Frequently asked 'How does itching in the body go?' The answer to the question can be given in this way. Just like in the treatment of itching, physical examination plays an important role in the treatment of bariatric surgery and may be due to chronic causes.")
        elif index==3:
            self.textEdit.setPlainText("What causes edema?\nEdema occurs because the tiny blood vessels (capillaries) in your body leak fluid. The leaking fluid is around the vein. accumulates in the tissues and causes swelling. Edema, which occurs in heart, liver and kidney diseases, is caused by the inability to remove salt, which holds the excess fluid in the body.\n\n\nHow is edema treated?\nMild edema usually goes away on its own. It is possible to accelerate the process by keeping the affected limb above the level of the heart. In the presence of more severe edema, it can be treated with drugs called diuretics, which help the body to remove excess fluid accumulated in the body through urine. However, since these drugs can cause side effects, they are used considering the general health status of the patient. These drugs offer a short-term solution. For permanent treatment, the factor causing edema should be determined and eliminated. For example, if edema has developed due to drug use, it may be necessary to discontinue them and start other drugs.")
        elif index==4:
            self.textEdit.setPlainText("What causes chest pain?\nWhen there is chest pain, the person's first thought is often that they are having a heart attack. While chest pain is an important symptom of a heart attack, it can also be caused by relatively less serious conditions. About 13% of visits to the emergency room for chest pain are due to a serious heart-related problem.\n\n\nHow are causes of chest pain diagnosed?\nThe key to diagnosis is the patient's medical history. Knowledge of the nature of the pain gives the doctor an idea of ​​what should be excluded and what is more likely. Understanding the nature of the pain, its severity, associated symptoms, and the risk factors present in the patient provides guidance in evaluating the likelihood of a potential cause and which diagnoses should be considered. To make a diagnosis, the doctor must know the type of pain and how much pain the person is experiencing. For this purpose, questions that can be asked to patients include:")
        elif index==5:
            self.textEdit.setPlainText("What is shortness of breath?\nShortness of breath, along with fatigue, is one of the most common complaints of patients. Shortness of breath means that the person is unable to breathe or has difficulty breathing. In other words, people think that their oxygen needs are not enough or that they are blocked while breathing. Other than that, some people may describe it as a heaviness and pressure in the chest. Shortness of breath can be divided into subjective and objective. Objective dyspnea is based on objective parameters. Oxygen level in the blood, blood gas or breathing rate during physical examination are the main criteria.\n\n\nHow is the treatment of shortness of breath planned?\nThere are widely used treatment methods for shortness of breath. However, it is of great importance to find the underlying disease and to plan the treatment for this picture under expert control. In the treatment of shortness of breath, first of all, if the person has gained weight, he/she should lose weight, if he/she smokes, quit smoking, and if his/her condition is low, he/she should be directed to exercises to increase the condition or to physical therapy.")
                                                                    
    def ArmE_22(self):
        self.textEdit.clear()
        index = self.ArmE_2.currentIndex()
        if index==1:     
            self.textEdit.setPlainText("What is cramp?\nCramping, also known as muscle spasm, is involuntary pain or contractions in the muscles. Muscles contract and relax to provide movement. Cramping occurs when a muscle contracting for movement contracts again without relaxing, or when the brain has problems transmitting the relaxation signal to the muscles. Unwanted and sudden muscle contractions can be observed in many muscle groups at the same time. Although cramps are more common in the front leg, hind leg and lower leg, they can also occur in the stomach, arms and hands. Everyone encounters cramping problem at least once in their life. It is more common in people who are involved in a particular sport, especially cyclists, marathon runners, and athletes.\n\n\nHow does the cramp go?\nCramping usually goes away with stretching movements applied to the muscles in the area where the cramp is experienced. In calf cramps, pushing the wall with both hands by pressing the heels on the ground and taking the cramped leg back half a step or pulling the foot from the ankle to the body in the lying position also help the cramp to pass. Gentle massage and hot compresses applied to the muscles help relax the muscles. If the cause of the muscle spasm is fluid and electrolyte loss, this loss must be replaced.")    
        elif index==2:
            self.textEdit.setPlainText("What is joint pain?\nAlthough joint pain is more common in older people, it is a health problem that can be encountered in younger individuals as well. Joint pain, which begins to appear with advancing age, is usually due to the decrease in joint fluid or the loss of strength of the cartilage tissue. Obesity, injuries and some diseases, intense sports activities can lead to joint damage and pain. Rarely, pain caused by psychological problems may also occur.\n\n\nWhat are the treatment methods for joint pain?\nHow to treat joint pain depends on the type of disease causing the pain. In addition to the symptomatic treatment applied to alleviate the pain and the accompanying negativities in the treatment, additional treatment should be applied for the disease causing the pain. Joint pain caused by rheumatic diseases can be treated with various drugs and physical therapy applications. Even spas are recommended for the treatment of some rheumatic diseases. It is very important to maintain weight control by eating regularly, as excess weight will cause more fatigue on the joints. Therefore, prevention of excessive weight gain is an important treatment method.")
        elif index==3:
            self.textEdit.setPlainText("What Are the Causes of Muscle Pain?\nMuscle pain, or in other words, soft tissue rheumatism, can occur either with strain on the muscles or with a disorder in the body's pain interpretation mechanisms such as fibromyalgia.\nOther diseases in which muscle pain is a prominent finding are myofascial pain syndrome polymyalgiaaromatica, myopathies and deficiencies of some vitamins such as vitamin D and some minerals such as magnesium. Iron deficiency anemia and thyroid disorders can also cause muscle pain complaints.\n\n\nWhat Should a Person Who Feels Muscle Pain Do?\nIn a person who feels muscle pain, first of all, it should be determined whether the pain is a local pain or a widespread pain.\nSince the cause of widespread pain may be rheumatic diseases such as fibromyalgia and myofascial pain syndrome, polymyalgiaaromatica or vitamin deficiencies, necessary tests should be performed after a good examination in such pains.\nIn regional muscle pain, the onset time of the pain and whether it is associated with any trauma should be determined. Traumas can be a major trauma such as a blow to the muscle or a fall, as well as unit traumas caused by the accumulation of repetitive small movements, which we call micro trauma. When a relationship is established with such a trauma, the patient can be followed up with muscle rest and cold application first.")
        
    def HandE_22(self):
        self.textEdit.clear()
        index = self.HandE_2.currentIndex()
        if index==1:  
            self.textEdit.setPlainText("What Causes Hand Cracking?\nHand care is a very important issue. Our hands can be damaged for many reasons, just like our face. Hands that are extremely open to external influences; It dries up in winter due to cold and harsh weather and can also be affected by extremely hot weather in summer. The main reason for hand cracking and drying is the loss of moisture due to external factors. Hands affected by summer and winter weather changes are left without moisture. Hands that are sensitive to cold and hot water can be extremely worn out, except for the seasonal factor. Cracks and wrinkles occur on the skin.\n\n\nWhat's Good for Cracked Hands?\nThe main cause of hand cracking is the lack of moisture in the skin. The first way to moisturize our skin is to consume plenty of water. If you do not meet your daily water needs, you may see dryness and cracking in certain parts of your body. Hand cracking is an example of this.\nAnother method that can be good for cracked hands is to use moisturizing creams and lotions. With OSL Hydrosoft Lotion, developed for both face and body, you can provide the moisture your hands need.")
        elif index==2:
            self.textEdit.setPlainText("How to understand a finger fracture?\nFingers, which are used for activities such as holding and grasping in the bone system, are one of the most sensitive points of the body. Finger fracture due to osteoporosis disease or environmental reasons goes unnoticed for a long time. Trauma, sports, workplace injury, falls or other accidents are the main causes of finger fractures.\n\n\nHOW IS FINGER FRACTURE TREATMENT DONE?\nFinger fractures require serious treatment. Even with a small breakage, it should be intervened immediately as it affects finger movements. Intervention varies with hands and feet. An x-ray is taken to determine the point where the fracture is. Then, an appropriate method is selected for the deformity caused by the fracture. Since the fracture experienced in finger fracture also affects other finger crowns, stabilizer treatment is applied to prevent the foot or hand from moving. Sensitive fingers are a little more difficult to re-weld than other bones. The scratch is fixed to the area where the broken bone is with screws, single and plate. It takes 4 or 6 weeks on average. In this process, not only drugs, but also the person should consume milk, greens and plenty of fruit.")
        elif index==3:
            self.textEdit.setPlainText("What Causes Nail Breakage?\nNails are like biomarkers of the body. The cause of nail breakage may be environmental factors to which the nails are exposed. However, some medical conditions detected in the body as a result of examinations and tests by the doctor may also be among the causes of nail breakage.\n\n\nWhat Is Good For Nail Breakage?\n'What's good for nail breakage?' In order to give a clear answer to the question 'Why does nail breakage happen?' The answer to the question should be sought. For this, you must go to the doctor's examination. Your doctor can apply the necessary treatment after performing the appropriate scans. If you observe that your nails are unhealthy, you can help prevent it with some home care strategies.")
             
    def LEGe_22(self):
        self.textEdit.clear()
        index = self.LEGe_2.currentIndex()
        if index==1:
            self.textEdit.setPlainText("What is Leg Numbness?\nLeg numbness is an uncomfortable complaint that usually occurs after prolonged sitting or crossing legs, resulting from pressure on the nerves or interruption of blood flow.\n\n\nHow Is Leg Numbness Treated?\nThe treatment for leg numbness varies according to the underlying condition of this condition. Antidepressant derivative drugs may be effective in cases of psychological leg numbness or fibromyalgia-induced leg numbness. While corticosteroid-derived drugs are used in inflammatory conditions, drugs containing gabapentin and pregabalin can be prescribed for the treatment of numbness caused by nerve damage such as MS or diabetic neuropathy.")
        elif index==2:
            self.textEdit.setPlainText("Why Do Legs Cramp?\nCramps can occur normally or as a result of a disease. Cramps are seen in the legs without any reason. The important thing here is that if the event in your tight, painful, cramped leg usually lasts more than 10 minutes, there is a problem that needs to be investigated.\nDehydration of the body is an event that triggers muscle cramps. Abnormal nerve activity is blamed for leg cramps of unknown cause.\n\n\nWhat Should We Do When Cramp Occurs?\nMost leg cramps can be relieved by working the affected muscles. Moving your legs as if you were exercising throughout the day often helps reduce the frequency of cramping attacks.\nAs soon as the legs cramp, it is necessary to stretch and massage the affected muscle. Stretching the leg by keeping it straight, lifting the feet back from the ankle, pulling the toes towards you, or getting out of bed and walking on the heels for a few minutes can cause a cramping fit.")
        elif index==3:
            self.textEdit.setPlainText("What Is Tingling In The Legs?\nIf there are complaints such as unbearable pain descending from your waist to your knee, tingling in the legs, difficulty in moving, the cause may be 'sciatica'. Sciatic pain, also called nerve rheumatism among the people, occurs in the sciatic nerve, which is the largest nerve in the body, and causes severe pain if it is compressed.\n\n\nHow Is Leg Numbness Treated?\nThe treatment for leg numbness varies according to the underlying condition of this condition. Antidepressant derivative drugs may be effective in cases of psychological leg numbness or fibromyalgia-induced leg numbness. While corticosteroid-derived drugs are used in inflammatory conditions, drugs containing gabapentin and pregabalin can be prescribed for the treatment of numbness caused by nerve damage such as MS or diabetic neuropathy.\nIn addition to medical treatment, there are various applications that can be done at home that answer the question of 'what is good for leg numbness'. Practices such as resting, massaging the relevant area, maintaining a sleep pattern, following a balanced and healthy diet, and limiting or ending alcohol consumption are among the methods that can be effective in controlling the complaint of numbness in the legs.\nYou should be aware of the need for urgent medical attention in case of a blunt pain sensation in the numb area, spreading from the leg to the groin, accompanied by severe complaints such as difficulty in walking and speaking.")
             
    def FOe_22(self):
        self.textEdit.clear()
        index = self.FOe_2.currentIndex()
        if index==1:   
            self.textEdit.setPlainText("What is Foot Fungus?\nFoot fungus, which can be defined as a fungal infection that occurs in the foot area of ​​the body, mostly develops between the toes. However, athlete's foot can also occur on the upper surface, side or back of the foot. This disorder, which is extremely common in society, is one of the health problems experienced by almost every individual once in a lifetime.\nFoot fungus initially causes red dots and scaly appearance on the skin surface. Following this situation, water-filled sacs occur on the feet. Extremely itchy bumps can take on an inflamed appearance. There may be rash and redness in the form of dandruff on the soles of the feet.\n\n\nHow to Treat Foot Fungus?\nThe priority in the treatment of athlete's foot is to protect foot health. In other words, the foot should be kept away from the environment where fungus can be transmitted. Feet should be washed regularly on a daily basis and thoroughly dried with a clean towel each time. Wearing shoes suitable for the season and changing socks when necessary are extremely effective in the treatment of athlete's foot.")
        elif index==2:
            self.textEdit.setPlainText("What Causes Foot Odor?\nNot the sweat itself, but the bacteria that comes with it, which is the main cause of bad foot odour. In addition to bacteria, fungal infection also causes the formation of a strong odor on the feet. Some medications used, hormonal changes during puberty or pregnancy; Metabolic diseases such as obesity, stress and hyperthyroidism also cause the body to produce more sweat, triggering foot odor. At the same time, genetic factors are also effective in foot odor.\n\n\nHow to Treat Foot Odor: With Sage!\nSage leaves have the feature of preventing foot odor. For this, you can put sage leaves in your shoes that you will use the night before.")
        elif index==3:
            self.textEdit.setPlainText("What Causes Ingrown Nails?\nAlthough ingrown nails are seen at the same rate in both men and women, it has been observed that it is more common in individuals with sweaty feet as a result of researches. In addition, elderly individuals are at higher risk, especially as toenails thicken with age.\n\n\nWhat is the treatment of ingrown nail?\nUninfected cases of ingrown toenails can be treated at home under normal circumstances. However, in cases where the toenail pierces the skin or shows any signs of infection, it is recommended to seek medical attention. Signs of infection include redness, swelling, warmth and pus.\nTo treat an ingrown nail, an individual can try soaking their feet in warm soapy water for about 15 to 20 minutes three to four times a day. But at other times the fingers should be kept dry. Placing a cotton ball dipped in olive oil into the space between the nail and the skin can help open up.")
        elif index==4:
            self.textEdit.setPlainText("What causes callus?\nCallus (callus and clavus) is the hardening and thickening of the skin that occurs as a result of the skin being under pressure and compression. Calluses can occur either due to the pressure of the bone protrusion under it or due to the pressure and compression applied to the same point constantly. Especially in cases such as the use of wrong shoes on the soles of the feet, the selection of inappropriate insoles, calluses may occur at the points where the body weight is most concentrated. If there is an anatomical deterioration in the bone structure, then calluses can also be observed.\n\n\nCallus Treatment\nCalluses can be treated using salicylic acid-containing mixtures, solutions, pomades and ready-made callus bands, which have the ability to dissolve the keratin layer of the skin. In cases where these applications are not sufficient, surgical removal of calluses, electrocautery or cryotherapy can be used to destroy them. Calluses can grow if left untreated. As a result of the addition of pain and infection, treatment can be difficult. Especially for patients with peripheral vascular disease, circulatory disorder and diabetes, calluses should be treated by specialist physicians. It should be kept in mind that wounds starting under the calluses in these patients may cause serious complications such as loss of limb.")
            
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Disease Diagnosis App", "Disease Diagnosis App"))
        self.tabWidget.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><img src=\"png.png\"/></p></body></html>"))
        self.tabWidget.setAccessibleName(_translate("MainWindow", "Man"))
        self.label.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><img src=\"png.png\"/></p></body></html>"))
        self.LEGe.setCurrentText(_translate("MainWindow", "Leg"))
        self.LEGe.setItemText(0, _translate("MainWindow", "Leg"))
        self.LEGe.setItemText(1, _translate("MainWindow", "numbness"))
        self.LEGe.setItemText(2, _translate("MainWindow", "cramp"))
        self.LEGe.setItemText(3, _translate("MainWindow", "tingle"))
        self.BodyE.setCurrentText(_translate("MainWindow", "Body"))
        self.BodyE.setItemText(0, _translate("MainWindow", "Body"))
        self.BodyE.setItemText(1, _translate("MainWindow", "Redness"))
        self.BodyE.setItemText(2, _translate("MainWindow", "Itching"))
        self.BodyE.setItemText(3, _translate("MainWindow", "Edema"))
        self.BodyE.setItemText(4, _translate("MainWindow", "Chest Pain"))
        self.BodyE.setItemText(5, _translate("MainWindow", "Shortness of breath"))
        self.ArmE.setCurrentText(_translate("MainWindow", "Arm"))
        self.ArmE.setItemText(0, _translate("MainWindow", "Arm"))
        self.ArmE.setItemText(1, _translate("MainWindow", "Cramp"))
        self.ArmE.setItemText(2, _translate("MainWindow", "Joint Pain"))
        self.ArmE.setItemText(3, _translate("MainWindow", "Muscle Pain"))
        self.FOe.setCurrentText(_translate("MainWindow", "Foot"))
        self.FOe.setItemText(0, _translate("MainWindow", "Foot"))
        self.FOe.setItemText(1, _translate("MainWindow", "athlete\'s foot"))
        self.FOe.setItemText(2, _translate("MainWindow", "foot odor"))
        self.FOe.setItemText(3, _translate("MainWindow", "ingrown toenails"))
        self.FOe.setItemText(4, _translate("MainWindow", "callus"))
        self.HandE.setCurrentText(_translate("MainWindow", "Hand"))
        self.HandE.setItemText(0, _translate("MainWindow", "Hand"))
        self.HandE.setItemText(1, _translate("MainWindow", "Hand Crack"))
        self.HandE.setItemText(2, _translate("MainWindow", "Finger Fracture"))
        self.HandE.setItemText(3, _translate("MainWindow", "Nail Break"))
        self.GAE.setCurrentText(_translate("MainWindow", "Genital Area"))
        self.GAE.setItemText(0, _translate("MainWindow", "Genital Area"))
        self.GAE.setItemText(1, _translate("MainWindow", "Burning while Urinating"))
        self.GAE.setItemText(2, _translate("MainWindow", "Swelling in the Groin"))
        self.GAE.setItemText(3, _translate("MainWindow", "Frequent Urination"))
        self.GAE.setItemText(4, _translate("MainWindow", "Wound in the Sexual Area"))
        self.HeadE.setCurrentText(_translate("MainWindow", "Head"))
        self.HeadE.setItemText(0, _translate("MainWindow", "Head"))
        self.HeadE.setItemText(1, _translate("MainWindow", "Headache"))
        self.HeadE.setItemText(2, _translate("MainWindow", "Defect of Vision"))
        self.HeadE.setItemText(3, _translate("MainWindow", "Tinnitus"))
        self.HeadE.setItemText(4, _translate("MainWindow", "Runny Nose"))
        self.HeadE.setItemText(5, _translate("MainWindow", "Sore Throat"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Man"))
        self.label_2.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><img src=\"png.png\"/></p></body></html>"))
        self.GAk.setCurrentText(_translate("MainWindow", "Genital Area"))
        self.GAk.setItemText(0, _translate("MainWindow", "Genital Area"))
        self.GAk.setItemText(1, _translate("MainWindow", "Burning while urinating"))
        self.GAk.setItemText(2, _translate("MainWindow", "Swelling"))
        self.GAk.setItemText(3, _translate("MainWindow", "Bleeding"))
        self.GAk.setItemText(4, _translate("MainWindow", "Itching"))
        self.HeadE_2.setCurrentText(_translate("MainWindow", "Head"))
        self.HeadE_2.setItemText(0, _translate("MainWindow", "Head"))
        self.HeadE_2.setItemText(1, _translate("MainWindow", "Headache"))
        self.HeadE_2.setItemText(2, _translate("MainWindow", "Defect of Vision"))
        self.HeadE_2.setItemText(3, _translate("MainWindow", "Tinnitus"))
        self.HeadE_2.setItemText(4, _translate("MainWindow", "Runny Nose"))
        self.HeadE_2.setItemText(5, _translate("MainWindow", "Sore Throat"))
        self.BodyE_2.setCurrentText(_translate("MainWindow", "Body"))
        self.BodyE_2.setItemText(0, _translate("MainWindow", "Body"))
        self.BodyE_2.setItemText(1, _translate("MainWindow", "Redness"))
        self.BodyE_2.setItemText(2, _translate("MainWindow", "Itching"))
        self.BodyE_2.setItemText(3, _translate("MainWindow", "Swelling"))
        self.BodyE_2.setItemText(4, _translate("MainWindow", "Chest Pain"))
        self.BodyE_2.setItemText(5, _translate("MainWindow", "Shortness of breath"))
        self.ArmE_2.setCurrentText(_translate("MainWindow", "Arm"))
        self.ArmE_2.setItemText(0, _translate("MainWindow", "Arm"))
        self.ArmE_2.setItemText(1, _translate("MainWindow", "Cramp"))
        self.ArmE_2.setItemText(2, _translate("MainWindow", "Joint Pain"))
        self.ArmE_2.setItemText(3, _translate("MainWindow", "Muscle Pain"))
        self.HandE_2.setCurrentText(_translate("MainWindow", "Hand"))
        self.HandE_2.setItemText(0, _translate("MainWindow", "Hand"))
        self.HandE_2.setItemText(1, _translate("MainWindow", "Hand Crack"))
        self.HandE_2.setItemText(2, _translate("MainWindow", "Peeling"))
        self.HandE_2.setItemText(3, _translate("MainWindow", "Finger Fracture"))
        self.HandE_2.setItemText(4, _translate("MainWindow", "Nail Break"))
        self.LEGe_2.setCurrentText(_translate("MainWindow", "Leg"))
        self.LEGe_2.setItemText(0, _translate("MainWindow", "Leg"))
        self.LEGe_2.setItemText(1, _translate("MainWindow", "sprain"))
        self.LEGe_2.setItemText(2, _translate("MainWindow", "numbness"))
        self.LEGe_2.setItemText(3, _translate("MainWindow", "cramp"))
        self.LEGe_2.setItemText(4, _translate("MainWindow", "tingle"))
        self.FOe_2.setCurrentText(_translate("MainWindow", "Foot"))
        self.FOe_2.setItemText(0, _translate("MainWindow", "Foot"))
        self.FOe_2.setItemText(1, _translate("MainWindow", "athlete\'s foot"))
        self.FOe_2.setItemText(2, _translate("MainWindow", "foot odor"))
        self.FOe_2.setItemText(3, _translate("MainWindow", "ingrown toenails"))
        self.FOe_2.setItemText(4, _translate("MainWindow", "callus"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Woman"))
